// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkR9DxhLvnEP0kyPsO2lzBsFYW7KOGZ2U',
    appId: '1:2760155798:web:96836f69e0d44abe1858b7',
    messagingSenderId: '2760155798',
    projectId: 'whopayed',
    authDomain: 'whopayed.firebaseapp.com',
    storageBucket: 'whopayed.appspot.com',
    measurementId: 'G-VHPHK5HD0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-XCdqI_Y5VPQs7mSnZ0suQ1ZGFqjKtOU',
    appId: '1:2760155798:android:869823028eac699a1858b7',
    messagingSenderId: '2760155798',
    projectId: 'whopayed',
    storageBucket: 'whopayed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHQtDTloSXgMuxKxQHCA_zTITHvebxdH4',
    appId: '1:2760155798:ios:e8543713bd593f591858b7',
    messagingSenderId: '2760155798',
    projectId: 'whopayed',
    storageBucket: 'whopayed.appspot.com',
    iosClientId:
        '2760155798-v925e756iprprpqu7o3f015h7iecr7ne.apps.googleusercontent.com',
    iosBundleId: 'com.whopayed.fisis.whopayed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHQtDTloSXgMuxKxQHCA_zTITHvebxdH4',
    appId: '1:2760155798:ios:e8543713bd593f591858b7',
    messagingSenderId: '2760155798',
    projectId: 'whopayed',
    storageBucket: 'whopayed.appspot.com',
    iosClientId:
        '2760155798-v925e756iprprpqu7o3f015h7iecr7ne.apps.googleusercontent.com',
    iosBundleId: 'com.whopayed.fisis.whopayed',
  );
}
